name: Reinit

on:
  workflow_dispatch:  # Manually trigger the workflow
 #push:

defaults:
  run:
    working-directory: .

jobs:
  run-release:
    if: ${{ github.run_number }} > 10
    runs-on: ubuntu-latest
    #needs: run-build
    steps:
      - uses: actions/checkout@v4

      - name: config
        run: |
            git config --global user.name ${{vars.U_ID}}
            git config --global user.email ${{ secrets.EMAIL }}                    

      - name: Restore state
        run: |
          echo ${{ github.run_number }}
      
          git checkout --orphan tempbranch
          git add -A
          git commit -m "Initial commit"
          git branch -D master
          git branch -m master
          git push -f origin master

      - name: Clean up
        run: |
          git fetch origin --prune
      