name: Python yml

on:
    workflow_dispatch:  # Manually trigger the workflow
    push:

defaults:
  run:
    shell: bash        
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: config
        run: |
            #git config pull.ff only
            git config user.name ${{vars.U_ID}}
            git config user.email ${{ secrets.EMAIL }}        
            git pull

      - name: run
        run: python3 app.py      

      - name: commit
        working-directory: ./out
        run: |
            git add -A
            timestamp=$(date -u)
            git commit -m "Latest data: ${timestamp}" || exit 0
            git push
    


  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout source 
        uses: actions/checkout@v4
        with:
            path: out

      - name: list files
        shell: bash
        run: |
          #cp -aT out/ pub/
          ls out/

      - name: Copy common files to new repo
        shell: bash
        working-directory: out
        run: |
            git config user.name ${{vars.U_ID}}
            git config user.email ${{ secrets.EMAIL }}       
            git remote add main https://github.com/heyjeffrey/world.git
            # git pull
            git add -A
            git commit -m "maint: Updated common files from ref: ${{ github.ref}}" || exit 0
            git push -f main master

